version: '3.8'

services:
  # 1. Container Aplikasi (Backend Laravel 13 & PHP 8.4 + Node.js 24)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: superposko-app
    user: "1000:1000"
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9090:8000"
      - "5173:5173"
    volumes:
      - ./:/var/www/html:Z
    networks:
      apps-network:
        ipv4_address: 10.20.2.20

  # 2. Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: superposko-nginx
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html:Z
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:Z
    depends_on:
      - app
    networks:
      apps-network:
        ipv4_address: 10.20.2.10

  # 3. Database Server (MySQL)
  mysql:
    image: mysql:8.4
    container_name: superposko-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_superposko
      MYSQL_USER: superposko_user
      MYSQL_PASSWORD: superposko_password
      MYSQL_ROOT_PASSWORD: root_password_superposko
    ports:
      - "3306:3306"
    volumes:
      - superposko-db-data:/var/lib/mysql:Z
    networks:
      apps-network:
        ipv4_address: 10.20.2.30

networks:
  apps-network:
    external: true

volumes:
  superposko-db-data:
