services:
  # 1. Container Aplikasi (Backend Laravel 13 & PHP 8.4 + Node.js 24)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: superposko-app
    user: "1000:1000"
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9090:8000"
      - "5173:5173"
    volumes:
      - ./:/var/www/html:Z
    networks:
      - superposko-network
      - database
      - backend

  # 2. Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: superposko
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www/html:Z
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:Z
    depends_on:
      - app
    networks:
      - superposko-network
      - proxy

networks:
  superposko-network:
    driver: bridge
  proxy:
    external: true
  backend:
    external: true
  database:
    external: true
